using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum AudioType
{
	None = -1,

	//Music
	LobbyBGM,
	MachineBGM,

	//Bet
	AddBet1,
	AddBet2,
	AddBet3,
	AddBet4,
	AddBet5,
	AddBet6,
	AddBet7,
	AddBet8,
	AddBet9,
	MinusBet1,
	MinusBet2,
	MinusBet3,
	MinusBet4,
	MinusBet5,
	MinusBet6,
	MinusBet7,
	MinusBet8,
	MinusBet9,

	//Reel
	SpinReel1,
	SpinReel2,
	SpinReel3,
	SpinReel4,
	StopReel,
	StopReelSpecial1,
	StopReelSpecial2,
	HypeSpin,
	HypeEnd,
	HypeSpin1Reel,
	HypeSpin2Reel,

	//Win
	BigWin,
	MegaWin,
	EpicWin,
	NormalHighWin,
	NormalLowWin,
//	CreditsTick,
//	CreditsTickEnd,

	//Common
	ParticleFly,

	//Small Games
	FreeSpinSwitch,
	FreeSpinSpinReel,
	RewindSwitch,
	RewindSpinReel,
	SlideSymbol,

	WheelTick,
	WheelSpin,
	WheelSpinWinCoin,
	CreditsRollUp,
	Click,
	// effect
	Frozen,
	M8_BreakIce,
	CollectGlass,
	LevelUp,
	M6_Freespin,
	FreeSpinSwitch2,
	M9_NormalBGM_Beginning,
	M9_NormalBGM_Loop,
	M9_Freespin,
	Calendar,
	DailyBonus,
	PiggyBankOpen,
	PiggyBankAppear,
	Last5Second,
	TournamentCollect,
	CollectFBGift,
	M10_SpinWheel,
	M10_WheelBGM,
	M10_WheelResult,
	DailyBonusCreditsRollUp,
	HourlyBonusCreditsRollUp,
	PiggyBankFakeOpen,
	M12_Dragon_Win,
	M12_FreespinDragonReady,
	M12_FreeSpinSwitch,
	M12_Freespin_Start,
	M12_Freespin_Loop,
	M12Box_Win,
	NormalRespinWin,
	M13LockWild,
	M13UnlockWild,
	M5_SpinReel1,
	M5_SpinReel2,
	M5_SpinReel3,
	M8_SpinReel1,
	M8_SpinReel2,
	M8_SpinReel3,
	M9_SpinReel1,
	M9_SpinReel2,
	M9_SpinReel3,
	M18_SpinReel1,
	M18_SpinReel2,
	M18_SpinReel3,
	M26_LockWild,
	M26_UnlockWild,
	M32_SpinReel1,
	M32_SpinReel2,
	M32_SpinReel3,
	MailBoxCollectCredits,
	M14_ButterFlying,
	M14_FreeSpinSwitch,
	M37_hit,
	M37_up,
	M37_down,
	M40_TapBoxBGM,
	M40_CollectCandy,
	M40_TapBoxCollectSuccess,
	M40_TapBoxCollectFail,
	M40_TapBoxPrologue,
	M41_Freespin,
	CrazyDiceCreditsResult,
	CrazyDiceTimesResult,
	RollCrazyDice,
	M20_TapChipBGM,
	M20_TapChipSuccess,
	M20_TapChipFail,
	M17_FreeSpinSwitch,
	M42_SpinReel1,
	M42_SpinReel2,
	M42_SpinReel3,
	M42_NormalBGM_Beginning,
	M42_NormalBGM_Loop,
	M24_SpinReel1,
	M24_SpinReel2,
	M24_SpinReel3,
	M42_GirlWild,
	M42_OpenGifts,
	M42_SantaClaus,
	M25_FreeSpinSwitch,
	M25_FreeSpin_Loop,
	Machine_SpinReel1,
	Machine_SpinReel2,
	Machine_SpinReel3,
	M34_Freespin,
	M36_Freespin_Start,
	M36_Freespin_Loop,
	M34_RespinEffect,
	//Add it before Count
	M30_FreespinBGM,
	M30_FreespinSwitch,
	Count
}

public class AudioDefine
{
	public static int MaxBetSound = 9;
}
